// Code generated by routergen; DO NOT EDIT.

package draftrag

import (
	"context"

	"github.com/bzdvdn/draftrag/internal/application"
)

var retrieveHandlers = map[route]func(context.Context, string, int, *SearchBuilder) (rRetrieve, error){
	routeBasic:        mkRetrieve((*application.Pipeline).Query),
	routeRewriter:     wrapRetrieve(rewriterRetrieve),
	routeSubDecompose: wrapRetrieve(subDecomposeRetrieve),
	routeHyDE:         mkRetrieve((*application.Pipeline).QueryHyDE),
	routeMultiQuery:   wrapRetrieve(multiQueryRetrieve),
	routeTools:        wrapRetrieve(toolsRetrieve),
	routeHybrid:       wrapRetrieve(hybridRetrieve),
	routeParentIDs:    wrapRetrieve(parentIDsRetrieve),
	routeFilter:       wrapRetrieve(filterRetrieve),
}
var answerHandlers = map[route]func(context.Context, string, int, *SearchBuilder) (rAnswer, error){
	routeBasic:        mkAnswer((*application.Pipeline).Answer),
	routeRewriter:     wrapAnswer(rewriterAnswer),
	routeSubDecompose: wrapAnswer(subDecomposeAnswer),
	routeHyDE:         mkAnswer((*application.Pipeline).AnswerHyDE),
	routeMultiQuery:   wrapAnswer(multiQueryAnswer),
	routeTools:        wrapAnswer(toolsAnswer),
	routeHybrid:       wrapAnswer(hybridAnswer),
	routeParentIDs:    wrapAnswer(parentIDsAnswer),
	routeFilter:       wrapAnswer(filterAnswer),
}
var citeHandlers = map[route]func(context.Context, string, int, *SearchBuilder) (rCite, error){
	routeBasic:        mkCite((*application.Pipeline).AnswerWithCitations),
	routeRewriter:     wrapCite(rewriterCite),
	routeSubDecompose: wrapCite(subDecomposeCite),
	routeHyDE:         mkCite((*application.Pipeline).AnswerHyDEWithCitations),
	routeMultiQuery:   wrapCite(multiQueryCite),
	routeTools:        wrapCite(toolsCite),
	routeHybrid:       wrapCite(hybridCite),
	routeParentIDs:    wrapCite(parentIDsCite),
	routeFilter:       wrapCite(filterCite),
}
var inlineCiteHandlers = map[route]func(context.Context, string, int, *SearchBuilder) (rInlineCite, error){
	routeBasic:        mkInlineCite((*application.Pipeline).AnswerWithInlineCitations),
	routeRewriter:     wrapInlineCite(rewriterInlineCite),
	routeSubDecompose: wrapInlineCite(subDecomposeInlineCite),
	routeHyDE:         mkInlineCite((*application.Pipeline).AnswerHyDEWithInlineCitations),
	routeMultiQuery:   wrapInlineCite(multiQueryInlineCite),
	routeTools:        wrapInlineCite(toolsInlineCite),
	routeHybrid:       wrapInlineCite(hybridInlineCite),
	routeParentIDs:    wrapInlineCite(parentIDsInlineCite),
	routeFilter:       wrapInlineCite(filterInlineCite),
}
var streamHandlers = map[route]func(context.Context, string, int, *SearchBuilder) (rStream, error){
	routeBasic:        mkStream((*application.Pipeline).AnswerStream),
	routeRewriter:     wrapStream(rewriterStream),
	routeSubDecompose: wrapStream(subDecomposeStream),
	routeHyDE:         mkStream((*application.Pipeline).AnswerHyDEStream),
	routeMultiQuery:   wrapStream(multiQueryStream),
	routeTools:        wrapStream(toolsStream),
	routeHybrid:       wrapStream(hybridStream),
	routeParentIDs:    wrapStream(parentIDsStream),
	routeFilter:       wrapStream(filterStream),
}
var streamSourcesHandlers = map[route]func(context.Context, string, int, *SearchBuilder) (rStreamSources, error){
	routeBasic:        mkStreamSources((*application.Pipeline).AnswerStreamWithSources),
	routeRewriter:     wrapStreamSources(rewriterStreamSources),
	routeSubDecompose: wrapStreamSources(subDecomposeStreamSources),
	routeHyDE:         mkStreamSources((*application.Pipeline).AnswerHyDEStreamWithSources),
	routeMultiQuery:   wrapStreamSources(multiQueryStreamSources),
	routeTools:        wrapStreamSources(toolsStreamSources),
	routeHybrid:       wrapStreamSources(hybridStreamSources),
	routeParentIDs:    wrapStreamSources(parentIDsStreamSources),
	routeFilter:       wrapStreamSources(filterStreamSources),
}
var streamCiteHandlers = map[route]func(context.Context, string, int, *SearchBuilder) (rStreamCite, error){
	routeBasic:        mkStreamCite((*application.Pipeline).AnswerStreamWithInlineCitations),
	routeRewriter:     wrapStreamCite(rewriterStreamCite),
	routeSubDecompose: wrapStreamCite(subDecomposeStreamCite),
	routeHyDE:         mkStreamCite((*application.Pipeline).AnswerHyDEStreamWithInlineCitations),
	routeMultiQuery:   wrapStreamCite(multiQueryStreamCite),
	routeTools:        wrapStreamCite(toolsStreamCite),
	routeHybrid:       wrapStreamCite(hybridStreamCite),
	routeParentIDs:    wrapStreamCite(parentIDsStreamCite),
	routeFilter:       wrapStreamCite(filterStreamCite),
}
