package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"text/template"
)

// @sk-task arch-issues#T5.1: router code generator (AC-005, AC-006)

const outputFile = "search_routes_gen.go"

const sourceTemplate = `// Code generated by routergen; DO NOT EDIT.

package draftrag

import (
	"context"

	"github.com/bzdvdn/draftrag/internal/application"
)
{{ range $col := .Columns }}
var {{ $col.Name | lowerFirst }}Handlers = map[route]func(context.Context, string, int, *SearchBuilder) ({{ $col.ResultType }}, error){
	{{- range $e := $.Entries }}
	{{ $e.Route }}: {{ if eq $e.Pattern "mk" }}mk{{ $col.Wrapper }}((*application.Pipeline).{{ index $e.Targets $col.Name }}){{ else }}wrap{{ $col.Wrapper }}({{ index $e.Targets $col.Name }}){{ end }},
	{{- end }}
}
{{- end }}
`

type entryData struct {
	Route   string
	Pattern string
	Targets map[string]string // column name -> handler/target name
}

type columnData struct {
	Name       string
	Wrapper    string
	ResultType string
}

type tmplData struct {
	Columns []columnData
	Entries []entryData
}

func main() {
	outPath := outputFile

	var entries []entryData
	for _, r := range routeTable {
		e := entryData{
			Route:   r.Route,
			Pattern: r.Pattern,
			Targets: make(map[string]string),
		}
		e.Targets["Retrieve"] = r.Retrieve
		e.Targets["Answer"] = r.Answer
		e.Targets["Cite"] = r.Cite
		e.Targets["InlineCite"] = r.InlineCite
		e.Targets["Stream"] = r.Stream
		e.Targets["StreamSources"] = r.StreamSources
		e.Targets["StreamCite"] = r.StreamCite
		entries = append(entries, e)
	}

	var columns []columnData
	for _, c := range outputColumns {
		columns = append(columns, columnData(c))
	}

	data := tmplData{Columns: columns, Entries: entries}

	funcMap := template.FuncMap{"lowerFirst": lowerFirst}
	tmpl := template.Must(template.New("routes").Funcs(funcMap).Parse(sourceTemplate))

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		fmt.Fprintf(os.Stderr, "template execute: %v\n", err)
		os.Exit(1)
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n%s\n", err, buf.String())
		os.Exit(1)
	}

	if err := os.WriteFile(outPath, src, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("generated %s\n", outputFile)
}

func lowerFirst(s string) string {
	if len(s) == 0 {
		return s
	}
	return string(s[0]+'a'-'A') + s[1:]
}
